---
- hosts: localhost
  become: yes

  pre_tasks:
  - name: Gather custom facts
    include: custom_facts.yml

  roles:
  - vmwaretools
  - vim
  - git
  - vscode
  - docker
  - shell
  - python

  post_tasks:
  - name: Remove passwordless sudo
    file:
      path: /etc/sudoers.d/passwordless-sudo
      state: absent
