---
- hosts: localhost
  become: yes

  pre_tasks:
  - name: Get current user
    shell:
      cmd: who | awk '/:0/{print $1}'
    changed_when: false
    register: current_user
  
  - name: Set custom facts
    set_fact:
      current_user: "{{ current_user.stdout }}"
      current_user_home: "/home/{{ current_user.stdout }}"

  roles:
  - vmwaretools
  - vim
  - git
  - vscode
  - docker
  - shell
