---
- hosts: localhost
  become: yes

  pre_tasks:
  - name: Gather custom facts
    include: custom_facts.yml

  roles:
  - vmwaretools
  - vim
  - git
  - vscode
  - docker
  - shell
  - python
  - virtualbox
  - vagrant

  post_tasks:
  - name: Remove passwordless sudo
    file:
      path: /etc/sudoers.d/passwordless-sudo
      state: absent
  
  - name: Reboot
    shell:
      cmd: shutdown -r 1
    when: reboot_required
