---
- name: Check Vagrant version
  shell: /usr/bin/vagrant --version | awk '{print $2}'
  ignore_errors: true
  changed_when: false
  register: vagrant_check

- name: Install Vagrant
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ version }}/vagrant_{{ version }}_x86_64.deb"
  when: ansible_os_family == "Debian" and
        (vagrant_check.rc != 0 or vagrant_check.stdout != version)
