---

- name: Install apt HTTPS support
  package:
    name: apt-transport-https
    state: present

- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  notify:
    - update apt cache
