---

- name: Add Microsoft GPG key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    enabled: yes
    register: repository

- name: Make yum cache
  command: yum makecache
  when: repository.changed