---
# Install and configure vscode

- name: Install Visual Studio Code
  package:
    name: code
    state: present

- name: Install extensions
  script: install_extensions.py ms-azuretools.vscode-docker ms-python.python vscoss.vscode-ansible
  register: install_extensions
  changed_when: install_extensions.stdout
  become: no

- name: Configure settings.json
  template:
    src: settings.json
    dest: "{{ current_user_home }}/.config/Code/User/settings.json"
  become: no
