---
# Install and configure vscode

- name: Install Visual Studio Code
  package:
    name: code
    state: present

- name: Get installed extensions
  script: get_extensions.py
  register: get_extensions
  check_mode: no
  changed_when: no
  become: no

- name: Set desired extension fact
  set_fact:
    desired_extensions: "{{ extensions | sort() | join(' ') }}"

- name: Install extensions
  script: install_extensions.py 
  register: install_extensions
  when: get_extensions.stdout != desired_extensions
  become: no

- name: Configure settings.json
  template:
    src: settings.json
    dest: "{{ current_user_home }}/.config/Code/User/settings.json"
  become: no
