---
- name: Add sources
  apt_repository:
    repo: deb-src http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted
    state: present
        
- name: Install Python build dependencies
  apt:
    name: python3
    state: build-dep

- name: Install other Python build dependencies
  apt:
    name: [   
           'libbz2-dev',
           'libffi-dev',
           'libgdbm-compat-dev',
           'libgdbm-dev',
           'liblzma-dev',
           'libncurses5-dev',
           'libreadline-dev',
           'libsqlite3-dev',
           'libssl-dev',
           'tk-dev',
           'uuid-dev',
           'zlib1g-dev',
          ]
    state: present