---
# tasks file for roles/git

- name: Install git
  package:
    name: git
    state: present

- name: Configure git username
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"
  when: '"enthalpy" in current_user'
  become: no

- name: Configure git email
  git_config:
    name: user.email
    scope: global
    value: "{{ user_email }}"
  when: '"enthalpy" in current_user'
  become: no

- name: Configure git editor
  git_config:
    name: core.editor
    scope: global
    value: "{{ core_editor }}"
  become: no
