---

- name: Install apt HTTPS support
  package:
    name: apt-transport-https
    state: present

- name: Add Oracle GPG key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add VirtualBox repository
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: present
    filename: vscode
    update_cache: yes