---
# tasks file for roles/vmwaretools

- name: Install VMware tools
  package:
    name: open-vm-tools
    state: present
  when: ansible_virtualization_type == "VMware"

- name: Install VMware tools (desktop)
  package:
    name: open-vm-tools-desktop
    state: present
  when: ansible_virtualization_type == "VMware"
